### ISSUE TITLE
edns-buffer-size difference: does it matter?

### ISSUE THREAD

**Issue by pimvh** [anudeepND/pihole-unbound#10]
Thanks for this guide on how to configure upbound!

I have a quick question though. I noticed a difference between your configuration and the default [pi-hole docs](https://docs.pi-hole.net/guides/dns/unbound/) on the edns-buffer-size. 

Your conf file sets it at _1232_, while the pihole docs set it at _1472_ (it says it's recommended by the upbound docs, but I've been unable to find it). Does this difference matter?

**Comment by asterix778** [comment]
[Unbound nlnetlabs.nl documentation](https://nlnetlabs.nl/documentation/unbound/unbound.conf/) 

in this documentation is the following written
Hope you are helped with this

> edns-buffer-size: <number>
              Number  of bytes size to advertise as the EDNS reassembly buffer
              size.  This is the value put into  datagrams  over  UDP  towards
              peers.   The actual buffer size is determined by msg-buffer-size
              (both for TCP and UDP).  Do not  set  higher  than  that  value.
              Default  is  1232 which is the DNS Flag Day 2020 recommendation.
              Setting to 512 bypasses even the most stringent path  MTU  prob-
              lems,  but  is seen as extreme, since the amount of TCP fallback
              generated is excessive (probably also for  this  resolver,  con-
              sider tuning the outgoing tcp number).

**Comment by pimvh** [comment]
Thanks for pointing me to the right spot in the docs, was unable to find it.

However, my original question still stands. I suppose the +- 200 bytes are not noticeable when using it, but isn't setting it to a lower value less efficient (as done in the [piHole](https://docs.pi-hole.net/guides/dns/unbound/) documentation, or is that dependant on the devices attached?

**Comment by bytesortierer** [comment]
Hi all,

I ask Google and Google answerd this:

An EDNS buffer size of 1232 bytes will avoid fragmentation on nearly all current networks. This is based on an MTU of 1280, which is required by the IPv6 specification, minus 48 bytes for the IPv6 and UDP headers and the aforementioned research.
Note that this recomendation is for a default value, to be used when better information is not available. Operators may still configure larger values if their networks support larger data frames and they are certain there is no risk of IP fragmentation. DNS server vendors may use higher (or lower) packet sizes if better information about the MTU is available from the kernel.

Source: https://dnsflagday.net/2020/

Regards

Marc


Auf Twitter folgen:
https://twitter.de/marc_krueger
Am 18. Feb. 2021, 21:48 +0100 schrieb Pim van Helvoirt <notifications@github.com>:

**Comment by pimvh** [comment]
Well, I am certainly lacking proper Google skills. Thanks to you both. I'll close this issue.
