### ISSUE TITLE
Pls update to latest Version 1.9.6

### ISSUE THREAD

**Issue by manuvaidya** [anudeepND/pihole-unbound#4]
Hi Anudeep, i am your Unbound user since long time.
i have observed that your Unbound version is way too old.
Unbound current version is 1.9.6.
i tried installing using manually from different guides. but no use.
can you pls update the Version in your repository to latest one pls ?

Thanks in Advance

**Comment by anudeepND** [comment]
@manuvaidya sudo apt install unbound will install the latest version depending on your OS.
