### ISSUE TITLE
Potential duplicate configuration inside Configure unbound section

### ISSUE THREAD

**Issue by aphichat-w** [anudeepND/pihole-unbound#5]
I've notice that there seem to be a duplicated setting inside /etc/unbound/unbound.conf.d/pi-hole.conf 

There're 2 
>msg-cache-size 
>rrset-cache-size
#
    # Time to live minimum for RRsets and messages in the cache. If the minimum
    # kicks in, the data is cached for longer than the domain owner intended,
    # and thus less queries are made to look up the data. Zero makes sure the
    # data in the cache is as the domain owner intended, higher values,
    # especially more than an hour or so, can lead to trouble as the data in
    # the cache does not match up with the actual data anymore
    cache-min-ttl: 300
    cache-max-ttl: 86400
    msg-cache-size: 128m
    rrset-cache-size: 256m

#

    # more cache memory. rrset-cache-size should twice what msg-cache-size is.
    msg-cache-size: 50m
    rrset-cache-size: 100m
#

is it supposed to be this way? I'm new to this unbound thing

**Comment by anudeepND** [comment]
Oops, it's a typo. Remove the duplicate and you're good to go. I will fix it in the next update
