### ISSUE TITLE
No internet after Pihole reboot

### ISSUE THREAD

**Issue by bhishma9988** [anudeepND/pihole-unbound#7]
The issue I am facing:
No internet after Pi reboot. After clicking DNS resolver internet begins to work

Details about my system:
Using Unbound DNS

Your debug token is: https://tricorder.pi-hole.net/9ubtfno584

**Comment by anudeepND** [comment]
Is there any errors in the config file? What is the output of `unbound-checkconf /etc/unbound/unbound.conf.d/pi-hole.conf`

**Comment by Killator** [comment]
You could check the rPi internal clock...
`timedatectl status`

... and resync manually if needed
```
sudo timedatectl set-ntp false
sudo timedatectl set-time 'Y-M-D HH:mm:ss'
sudo timedatectl set-ntp true
sudo reboot
```

**Comment by anudeepND** [comment]
Stale issue, closing
