### ISSUE TITLE
Update guide

### ISSUE THREAD

**Issue by Rar9** [anudeepND/pihole-unbound#9]
I found this guide

Is this still applieng with the lasted pihole?

Is  there still a requirement download  root.host every 4-6 months?

What are the Cache_size in setupVar.conf  for and do they need to be set to ZERO as well?

Your guide should mention what to reboot so the setting are applied.

Is there any way to check / test if all is working via unbound?

**Comment by Rar9** [comment]
![image](https://user-images.githubusercontent.com/2239608/109671853-bc451980-7b74-11eb-92d3-483242de6ce1.png)

I applied the 0 cache in pihole but still that something gets cached instead of being cached by unbound.

**Comment by bytesortierer** [comment]
Hi all,

I also do not know what is cached there.

Regards

**Comment by Rar9** [comment]
Ok I double check and it looks like pihole has updated the changed cache settings again to default.

One last question will Unbound auto-refresh the Root host list itself or will it might send to add a 4-6 month cron job to autoupdate this?

**Comment by bytesortierer** [comment]
Hello,

you have to do this manually or create a CronJob

Greetings
Marc

**Comment by v1rusnl** [comment]
> I found this guide
> 
> Is this still applieng with the lasted pihole?
> 
> Is there still a requirement download root.host every 4-6 months?
> 
> What are the Cache_size in setupVar.conf for and do they need to be set to ZERO as well?
> 
> Your guide should mention what to reboot so the setting are applied.
> 
> Is there any way to check / test if all is working via unbound?

You also need to set the CACHESIZE in setupVars.conf to 0. This was a users request since  /etc/dnsmasq.d/01-pihole.conf gets overwritten with an update, setupVars.conf stays like it is.

https://discourse.pi-hole.net/t/add-cache-size-to-setupvars-conf/28667

**Comment by anudeepND** [comment]
Sorry for the late reply. As per the developers, it is recommended to not make any changes to the pi-hole config so I have removed that section from the readme.
